export interface Municipality {
  name: string;
}

export interface Province {
  name: string;
  municipalities: Municipality[];
}

export const angolaProvinces: Province[] = [
  {
    name: "Luanda",
    municipalities: [
      { name: "Belas" },
      { name: "Cacuaco" },
      { name: "Cazenga" },
      { name: "Icolo e Bengo" },
      { name: "Luanda" },
      { name: "Quiçama" },
      { name: "Viana" },
    ],
  },
  {
    name: "Bengo",
    municipalities: [
      { name: "Ambriz" },
      { name: "Bula Atumba" },
      { name: "Dande" },
      { name: "Dembos" },
      { name: "Nambuangongo" },
      { name: "Pango Aluquém" },
    ],
  },
  {
    name: "Benguela",
    municipalities: [
      { name: "Balombo" },
      { name: "Baía Farta" },
      { name: "Benguela" },
      { name: "Bocoio" },
      { name: "Caimbambo" },
      { name: "Catumbela" },
      { name: "Chongoroi" },
      { name: "Cubal" },
      { name: "Ganda" },
      { name: "Lobito" },
    ],
  },
  {
    name: "Bié",
    municipalities: [
      { name: "Andulo" },
      { name: "Camacupa" },
      { name: "Catabola" },
      { name: "Chinguar" },
      { name: "Chitembo" },
      { name: "Cuemba" },
      { name: "Cunhinga" },
      { name: "Cuíto" },
      { name: "Nharea" },
    ],
  },
  {
    name: "Cabinda",
    municipalities: [
      { name: "Belize" },
      { name: "Buco-Zau" },
      { name: "Cabinda" },
      { name: "Cacongo" },
    ],
  },
  {
    name: "Cuando Cubango",
    municipalities: [
      { name: "Calai" },
      { name: "Cuangar" },
      { name: "Cuchi" },
      { name: "Cuito Cuanavale" },
      { name: "Dirico" },
      { name: "Mavinga" },
      { name: "Menongue" },
      { name: "Nankova" },
      { name: "Rivungo" },
    ],
  },
  {
    name: "Cuanza Norte",
    municipalities: [
      { name: "Ambaca" },
      { name: "Banga" },
      { name: "Bolongongo" },
      { name: "Cambambe" },
      { name: "Cazengo" },
      { name: "Golungo Alto" },
      { name: "Gonguembo" },
      { name: "Lucala" },
      { name: "Quiculungo" },
      { name: "Samba Cajú" },
    ],
  },
  {
    name: "Cuanza Sul",
    municipalities: [
      { name: "Amboim" },
      { name: "Cassongue" },
      { name: "Cela" },
      { name: "Conda" },
      { name: "Ebo" },
      { name: "Libolo" },
      { name: "Mussende" },
      { name: "Porto Amboim" },
      { name: "Quibala" },
      { name: "Quilenda" },
      { name: "Seles" },
      { name: "Sumbe" },
    ],
  },
  {
    name: "Cunene",
    municipalities: [
      { name: "Cahama" },
      { name: "Cuanhama" },
      { name: "Curoca" },
      { name: "Cuvelai" },
      { name: "Namacunde" },
      { name: "Ombadja" },
    ],
  },
  {
    name: "Huambo",
    municipalities: [
      { name: "Bailundo" },
      { name: "Cachiungo" },
      { name: "Caála" },
      { name: "Ecunha" },
      { name: "Huambo" },
      { name: "Londuimbali" },
      { name: "Longonjo" },
      { name: "Mungo" },
      { name: "Chicala-Choloanga" },
      { name: "Chinjenje" },
      { name: "Ucuma" },
    ],
  },
  {
    name: "Huíla",
    municipalities: [
      { name: "Caconda" },
      { name: "Cacula" },
      { name: "Caluquembe" },
      { name: "Chiange" },
      { name: "Chibia" },
      { name: "Chicomba" },
      { name: "Chipindo" },
      { name: "Cuvango" },
      { name: "Humpata" },
      { name: "Jamba" },
      { name: "Lubango" },
      { name: "Matala" },
      { name: "Quilengues" },
      { name: "Quipungo" },
    ],
  },
  {
    name: "Lunda Norte",
    municipalities: [
      { name: "Cambulo" },
      { name: "Capenda-Camulemba" },
      { name: "Caungula" },
      { name: "Chitato" },
      { name: "Cuango" },
      { name: "Cuílo" },
      { name: "Lóvua" },
      { name: "Lubalo" },
      { name: "Lucapa" },
      { name: "Xá-Muteba" },
    ],
  },
  {
    name: "Lunda Sul",
    municipalities: [
      { name: "Cacolo" },
      { name: "Dala" },
      { name: "Muconda" },
      { name: "Saurimo" },
    ],
  },
  {
    name: "Malanje",
    municipalities: [
      { name: "Cacuso" },
      { name: "Calandula" },
      { name: "Cambundi-Catembo" },
      { name: "Cangandala" },
      { name: "Caombo" },
      { name: "Cuaba Nzogo" },
      { name: "Cunda-Dia-Baze" },
      { name: "Lubango" },
      { name: "Luquembo" },
      { name: "Malanje" },
      { name: "Marimba" },
      { name: "Massango" },
      { name: "Mucari" },
      { name: "Quela" },
    ],
  },
  {
    name: "Moxico",
    municipalities: [
      { name: "Alto Zambeze" },
      { name: "Bundas" },
      { name: "Camanongue" },
      { name: "Cameia" },
      { name: "Léua" },
      { name: "Luau" },
      { name: "Luacano" },
      { name: "Luchazes" },
      { name: "Moxico" },
    ],
  },
  {
    name: "Namibe",
    municipalities: [
      { name: "Bibala" },
      { name: "Camucuio" },
      { name: "Moçâmedes" },
      { name: "Tômbwa" },
      { name: "Virei" },
    ],
  },
  {
    name: "Uíge",
    municipalities: [
      { name: "Alto Cauale" },
      { name: "Ambuíla" },
      { name: "Bembe" },
      { name: "Buengas" },
      { name: "Bungo" },
      { name: "Damba" },
      { name: "Kimbele" },
      { name: "Macocola" },
      { name: "Milunga" },
      { name: "Mucaba" },
      { name: "Negage" },
      { name: "Puri" },
      { name: "Quimbele" },
      { name: "Quitexe" },
      { name: "Sanza Pombo" },
      { name: "Songo" },
      { name: "Uíge" },
      { name: "Zombo" },
    ],
  },
  {
    name: "Zaire",
    municipalities: [
      { name: "Cuimba" },
      { name: "Mbanza Kongo" },
      { name: "Nóqui" },
      { name: "Nzeto" },
      { name: "Soio" },
      { name: "Tomboco" },
    ],
  },
];
